id: P001819
initial_creation_type: ocr
source_metadata:
  id: bdr:W30069
  title: རེབ་གོང་སྐྱབས་མགོན་བདུན་པ་བློ་བཟང་འཕྲིན་ལས་ལུང་རྟོགས་རྒྱ་མཚོའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    3d9e1015f5c94a718ebe58e0e91fe045:
      image_group_id: I1KG14632
      title: ''
      volume_number: 1
      total_pages: 148
