id: P001819
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:23:25.216628
source_metadata:
  id: bdr:W30069
  title: རེབ་གོང་སྐྱབས་མགོན་བདུན་པ་བློ་བཟང་འཕྲིན་ལས་ལུང་རྟོགས་རྒྱ་མཚོའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    3d9e1015f5c94a718ebe58e0e91fe045:
      image_group_id: I1KG14632
      title: ''
      volume_number: 1
      total_pages: 148
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
